name: End-to-end tests
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_baseUrl: 'https://deploy-preview-${{ github.event.number }}--nuxt-netlify-functions-example.netlify.app'
        with:
          record: false
          wait-on: 'https://deploy-preview-${{ github.event.number }}--nuxt-netlify-functions-example.netlify.app'
          wait-on-timeout: 90
